version: '3.1'

services:
  teslo-shop-api:
    container_name: teslo-shop-api
    build: .
    ports:
      - ${PORT}:${PORT}
    networks:
      - teslo-shop
    depends_on:
      - postgres-db
    environment:
      PORT: ${PORT}
      ENV: ${ENV}
      HOST: ${HOST}
      API_VERSION: ${API_VERSION}
      DB_HOST: postgres-db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}

  postgres-db:
    container_name: postgres-db
    image: postgres:14.3
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - teslo-shop
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata

networks:
  teslo-shop:

volumes:
  postgres-db-data:
    driver: local
