version: '3.1'

services:
  teslo-shop-api:
    container_name: teslo-shop-api
    image: stivenramireza/teslo-shop-api:1.0.0
    ports:
      - ${PORT}:${PORT}
    networks:
      - teslo-shop
    environment:
      PORT: ${PORT}
      ENV: ${ENV}
      HOST: ${HOST}
      API_VERSION: ${API_VERSION}
      DB_HOST: postgres-db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}

networks:
  teslo-shop:
