version: '3.1'

services:
  db:
    container_name: mongo
    image: mongo:5
    restart: always
    ports:
      - 27017:27017
    networks:
      - pokedex
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}

networks:
  pokedex:

volumes:
  mongo-data:
    driver: local
