version: '3.1'

services:
  pokedex-api:
    container_name: pokedex-api
    image: stivenramireza/pokedex-api:1.0.1
    ports:
      - ${PORT}:${PORT}
    networks:
      - pokedex
    environment:
      PORT: ${PORT}
      ENV: ${ENV}
      API_VERSION: ${API_VERSION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DEFAULT_LIMIT: ${DEFAULT_LIMIT}

networks:
  pokedex:
